# MiniNumPy Demo Notebook
**Project:** MiniNumPy Library


In [3]:
import MiniNumPy as mnp
import numpy as np

In [5]:
print("--- Reshape Test ---")
original = mnp.arange(0, 12) # 1D array
m_reshaped = original.reshape((3, 4))
n_reshaped = np.arange(0, 12).reshape((3, 4))

print("MiniNumPy (3x4):\n", m_reshaped)
print("NumPy (3x4):\n", n_reshaped)

--- Reshape Test ---
MiniNumPy (3x4):
 [
 0 1 2 3
 4 5 6 7
 8 9 10 11
]
NumPy (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print("--- Transpose Test ---")
print("MiniNumPy Transpose:\n", m_reshaped.transpose())
print("NumPy Transpose:\n", n_reshaped.T)

--- Transpose Test ---
MiniNumPy Transpose:
 [
 0 4 8
 1 5 9
 2 6 10
 3 7 11
]
NumPy Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [7]:
print("--- Basic Creation ---")
data = [[1, 2, 3], [4, 5, 6]]

print("MiniNumPy:\n", mnp.Array(data))
print("NumPy:\n", np.array(data))

--- Basic Creation ---
MiniNumPy:
 [
 1 2 3
 4 5 6
]
NumPy:
 [[1 2 3]
 [4 5 6]]


In [8]:
print("--- Zeros (2x3) ---")
print("MiniNumPy:\n", mnp.zeros((2, 3)))
print("NumPy:\n", np.zeros((2, 3)))

print("\n--- Ones (2x2) ---")
print("MiniNumPy:\n", mnp.ones((2, 2)))
print("NumPy:\n", np.ones((2, 2)))

--- Zeros (2x3) ---
MiniNumPy:
 [
 0 0 0
 0 0 0
]
NumPy:
 [[0. 0. 0.]
 [0. 0. 0.]]

--- Ones (2x2) ---
MiniNumPy:
 [
 1 1
 1 1
]
NumPy:
 [[1. 1.]
 [1. 1.]]


In [9]:
print("--- Identity Matrix (3x3) ---")
print("MiniNumPy:\n", mnp.eye(3))
print("NumPy:\n", np.eye(3))

print("\n--- Arange (0 to 10 step 2) ---")
print("MiniNumPy:\n", mnp.arange(0, 10, 2))
print("NumPy:\n", np.arange(0, 10, 2))

print("\n--- Linspace (0 to 1, 5 points) ---")
print("MiniNumPy:\n", mnp.linspace(0, 1, 5))
print("NumPy:\n", np.linspace(0, 1, 5))

--- Identity Matrix (3x3) ---
MiniNumPy:
 [
 1 0 0
 0 1 0
 0 0 1
]
NumPy:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- Arange (0 to 10 step 2) ---
MiniNumPy:
 Array([0, 2, 4, 6, 8])
NumPy:
 [0 2 4 6 8]

--- Linspace (0 to 1, 5 points) ---
MiniNumPy:
 Array([0.0, 0.25, 0.5, 0.75, 1.0])
NumPy:
 [0.   0.25 0.5  0.75 1.  ]


In [10]:
a = mnp.Array([[1, 2], [3, 4]])
b = mnp.Array([[10, 20], [30, 40]])
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

print("--- Addition (a + b) ---")
print("MiniNumPy:\n", a + b)
print("NumPy:\n", A + B)

print("\n--- Multiplication (a * b) ---")
print("MiniNumPy:\n", a * b)
print("NumPy:\n", A * B)

print("\n--- Broadcasting (a * 10) ---")
print("MiniNumPy:\n", a * 10)
print("NumPy:\n", A * 10)

--- Addition (a + b) ---
MiniNumPy:
 [
 11 22
 33 44
]
NumPy:
 [[11 22]
 [33 44]]

--- Multiplication (a * b) ---
MiniNumPy:
 [
 10 40
 90 160
]
NumPy:
 [[ 10  40]
 [ 90 160]]

--- Broadcasting (a * 10) ---
MiniNumPy:
 [
 10 20
 30 40
]
NumPy:
 [[10 20]
 [30 40]]


In [11]:
print("--- Exp ---")
print("MiniNumPy:\n", a.exp())
print("NumPy:\n", np.exp(A))

print("\n--- Log ---")
print("MiniNumPy:\n", a.log())
print("NumPy:\n", np.log(A))

print("\n--- Sqrt ---")
print("MiniNumPy:\n", a.sqrt())
print("NumPy:\n", np.sqrt(A))

--- Exp ---
MiniNumPy:
 [
 2.718281828459045 7.38905609893065
 20.085536923187668 54.598150033144236
]
NumPy:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

--- Log ---
MiniNumPy:
 [
 0.0 0.6931471805599453
 1.0986122886681098 1.3862943611198906
]
NumPy:
 [[0.         0.69314718]
 [1.09861229 1.38629436]]

--- Sqrt ---
MiniNumPy:
 [
 1.0 1.4142135623730951
 1.7320508075688772 2.0
]
NumPy:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [12]:
print("--- Max & Min ---")
print(f"MiniNumPy Max: {a.max()}, Min: {a.min()}")
print(f"NumPy Max:     {A.max()}, Min: {A.min()}")

print("\n--- Sum & Mean ---")
print(f"MiniNumPy Sum: {a.sum()}, Mean: {a.mean()}")
print(f"NumPy Sum:     {A.sum()}, Mean: {A.mean()}")

--- Max & Min ---
MiniNumPy Max: 4, Min: 1
NumPy Max:     4, Min: 1

--- Sum & Mean ---
MiniNumPy Sum: 10, Mean: 2.5
NumPy Sum:     10, Mean: 2.5


In [13]:
A_mat = mnp.Array([[1, 2], [3, 4]])
B_mat = mnp.Array([[2, 0], [1, 2]])

print("--- Matrix Multiplication (A @ B) ---")
print("MiniNumPy:\n", A_mat @ B_mat)
print("NumPy:\n", np.array(A_mat.tolist()) @ np.array(B_mat.tolist()))

--- Matrix Multiplication (A @ B) ---
MiniNumPy:
 [
 4 4
 10 8
]
NumPy:
 [[ 4  4]
 [10  8]]


In [14]:
import random
random.seed(42)
data_5x5 = [[random.random() for _ in range(5)] for _ in range(5)]
m_mat = mnp.Array(data_5x5)
n_mat = np.array(data_5x5)

m_det = mnp.det(m_mat)
n_det = np.linalg.det(n_mat)

print("--- Determinant of 5x5 Random Matrix ---")
print(f"MiniNumPy: {m_det:.6f}")
print(f"NumPy:     {n_det:.6f}")

--- Determinant of 5x5 Random Matrix ---
MiniNumPy: -0.085847
NumPy:     -0.085847


In [15]:
inv_data = [[4, 7], [2, 6]]
m_to_inv = mnp.Array(inv_data)
n_to_inv = np.array(inv_data)

print("--- Matrix Inverse ---")
m_inv = mnp.inv(m_to_inv)
print("MiniNumPy:\n", m_inv)
print("NumPy:\n", np.linalg.inv(n_to_inv))

print("\n--- Verification (A @ A_inv == Identity) ---")
print(m_to_inv @ m_inv)

--- Matrix Inverse ---
MiniNumPy:
 [
 0.6000000000000001 -0.7000000000000001
 -0.2 0.4
]
NumPy:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

--- Verification (A @ A_inv == Identity) ---
[
 1.0000000000000002 0.0
 0.0 1.0000000000000002
]
